const SUPABASE_URL = "https://yhyukqbkzwabkwzbrljq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_VikhSOb5A_e5hyJXC9AXLw_PuGfwR9g";
const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
const LEAGUES_KEY = "fantasyTrackerLeagues", BETS_KEY = "fantasyTrackerBets", DAILY_FANTASY_KEY = "fantasyTrackerDailyFantasy", MIGRATION_KEY = "fantasyTrackerCloudMigration";
let leagues = JSON.parse(localStorage.getItem(LEAGUES_KEY) || "[]");
let bets = JSON.parse(localStorage.getItem(BETS_KEY) || "[]").map(bet => ({ ...bet, type: bet.type || "Single", legs: Array.isArray(bet.legs) ? bet.legs : [] })), dailyFantasy = JSON.parse(localStorage.getItem(DAILY_FANTASY_KEY) || "[]"), currentUser = null, editingLeague = null, expandedLeagueId = null;

const currency = value => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value) || 0);
const escapeHtml = value => String(value ?? "").replace(/[&<>'"]/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" }[c]));
const positionClass = position => ["qb", "rb", "wr", "te", "k", "def"].includes(String(position).toLowerCase()) ? String(position).toLowerCase() : "player";
const getProfit = bet => bet.result === "Win" ? (Number(bet.odds) > 0 ? Number(bet.stake) * Number(bet.odds) / 100 : Number(bet.stake) * 100 / Math.abs(Number(bet.odds))) : bet.result === "Loss" ? -Number(bet.stake) : 0;
const getResultProfit = entry => entry.result === "Win" ? Number(entry.amount || 0) : entry.result === "Loss" ? -Number(entry.amount || 0) : 0;
function saveLocalData(){ localStorage.setItem(LEAGUES_KEY, JSON.stringify(leagues)); localStorage.setItem(BETS_KEY, JSON.stringify(bets)); localStorage.setItem(DAILY_FANTASY_KEY, JSON.stringify(dailyFantasy)); }
function showMessage(message, isError=false){ const el=document.getElementById("authMessage"); el.textContent=message; el.classList.toggle("error-message",isError); }
function setAuthUI(){ const signedIn=Boolean(currentUser); document.getElementById("authTitle").textContent=signedIn ? currentUser.email : "Sign in to sync"; document.getElementById("authForm").hidden=signedIn; document.getElementById("signOutButton").hidden=!signedIn; if(signedIn) showMessage("Synced across your signed-in devices."); }
function leagueToRow(l){ return {id:l.id,user_id:currentUser.id,name:l.name,platform:l.platform||null,team:l.team||null,buy_in:l.buyIn,status:l.status,result:l.result||"Pending",payout:l.amount||0,roster:l.roster||[]}; }
function rowToLeague(r){ return {id:r.id,name:r.name,platform:r.platform,team:r.team,buyIn:Number(r.buy_in),status:r.status,result:r.result||"Pending",amount:Number(r.payout||0),roster:Array.isArray(r.roster)?r.roster:[]}; }
function betToRow(b){ return {id:b.id,user_id:currentUser.id,bet_date:b.date,sport:b.sport,wager:b.wager,stake:b.stake,odds:b.odds,result:b.result,bet_type:b.type||"Single",legs:b.legs||[]}; }
function rowToBet(r){ return {id:r.id,date:r.bet_date,sport:r.sport,wager:r.wager,stake:Number(r.stake),odds:Number(r.odds),result:r.result,type:r.bet_type||"Single",legs:Array.isArray(r.legs)?r.legs:[]}; }
function dailyFantasyToRow(entry){ return {id:entry.id,user_id:currentUser.id,entry_date:entry.date,game_type:entry.type,slate:entry.slate,site:entry.site||null,result:entry.result,amount:entry.amount}; }
function rowToDailyFantasy(row){ return {id:row.id,date:row.entry_date,type:row.game_type,slate:row.slate,site:row.site,result:row.result,amount:Number(row.amount)}; }

function render(){
  const active=leagues.filter(l=>l.status==="Active").length, open=bets.filter(b=>b.result==="Pending").length, profit=bets.reduce((n,b)=>n+getProfit(b),0)+leagues.reduce((n,l)=>n+getResultProfit(l),0)+dailyFantasy.reduce((n,entry)=>n+getResultProfit(entry),0);
  document.getElementById("activeLeagues").textContent=active; document.getElementById("openBets").textContent=open; document.getElementById("netProfit").textContent=currency(profit);
  document.getElementById("leagueCount").textContent=`${leagues.length} ${leagues.length===1?"league":"leagues"}`; document.getElementById("betCount").textContent=`${bets.length} ${bets.length===1?"bet":"bets"}`;
  document.getElementById("leagueList").innerHTML=leagues.length?leagues.map(l=>`<article class="league-card"><div class="league-summary"><div class="league-name">${escapeHtml(l.name)}<small>${escapeHtml(l.team||"No team name")} · ${escapeHtml(l.platform||"Platform not set")}</small></div><div><small>Buy-in</small><br>${currency(l.buyIn)}</div><div><small>Season result</small><br><select class="result-select fantasy-result-select" data-id="${l.id}"><option ${l.result==="Pending"?"selected":""}>Pending</option><option ${l.result==="Win"?"selected":""}>Win</option><option ${l.result==="Loss"?"selected":""}>Loss</option></select></div><div><small>Net</small><br><input class="amount-input fantasy-amount-input" data-id="${l.id}" type="number" min="0" step="0.01" value="${Number(l.amount||0)}" aria-label="Net result for ${escapeHtml(l.name)}"></div><div><small>Roster</small><br>${l.roster.length} players</div><div><span class="status ${escapeHtml(l.status.toLowerCase())}">${escapeHtml(l.status)}</span></div><div class="league-actions"><button class="outline-button roster-button" data-id="${l.id}" aria-expanded="${expandedLeagueId===l.id}">${expandedLeagueId===l.id?"Hide":"View"} roster</button><button class="delete-button" data-type="league" data-id="${l.id}">Delete</button></div></div>${expandedLeagueId===l.id?`<div class="roster-preview" aria-label="${escapeHtml(l.team||l.name)} roster">${l.roster.length?`<div class="roster-preview-label">${l.roster.length} rostered player${l.roster.length===1?"":"s"}</div><div class="roster-preview-grid">${l.roster.map(p=>`<div class="roster-player"><span class="position-badge ${positionClass(p.position)}">${escapeHtml(p.position||"Player")}</span><span>${escapeHtml(p.name)}</span></div>`).join("")}</div>`:"<span class=\"empty-row\">No players added yet.</span>"}<button class="outline-button edit-roster" data-id="${l.id}">Edit roster</button></div>`:""}</article>`).join(""):"<div class=\"empty-row\">Add a league to begin tracking its roster.</div>";
  document.getElementById("dailyFantasyCount").textContent=`${dailyFantasy.length} ${dailyFantasy.length===1?"entry":"entries"}`;
  document.getElementById("dailyFantasyList").innerHTML=dailyFantasy.length?dailyFantasy.map(entry=>`<article class="daily-fantasy-entry"><div><strong>${escapeHtml(entry.type)}</strong><small>${escapeHtml(entry.date)} · ${escapeHtml(entry.slate)}${entry.site?` · ${escapeHtml(entry.site)}`:""}</small></div><select class="result-select daily-result-select" data-id="${entry.id}"><option ${entry.result==="Pending"?"selected":""}>Pending</option><option ${entry.result==="Win"?"selected":""}>Win</option><option ${entry.result==="Loss"?"selected":""}>Loss</option></select><input class="amount-input daily-amount-input" data-id="${entry.id}" type="number" min="0" step="0.01" value="${Number(entry.amount||0)}" aria-label="Net result for ${escapeHtml(entry.slate)}"><strong class="net-result ${entry.result.toLowerCase()}">${currency(getResultProfit(entry))}</strong><button class="delete-button" data-type="daily" data-id="${entry.id}">Delete</button></article>`).join(""):"<div class=\"empty-row\">Add a GPP, Showdown, or Cash Game to track it here.</div>";
  const sortedBets = [...bets].sort((a,b) => (b.result === "Pending") - (a.result === "Pending"));
  document.getElementById("betTableBody").innerHTML=sortedBets.length?sortedBets.map(b=>{
    const potentialProfit = Number(b.odds) > 0 ? Number(b.stake) * Number(b.odds) / 100 : Number(b.stake) * 100 / Math.abs(Number(b.odds));
    const legs = b.type === "Parlay" && b.legs.length ? `<ol class="parlay-legs">${b.legs.map(leg=>`<li>${escapeHtml(leg)}</li>`).join("")}</ol>` : "";
    return `<article class="bet-card ${b.type === "Parlay" ? "parlay-bet" : ""}"><div class="bet-card-main"><div class="bet-meta"><span class="bet-type ${b.type.toLowerCase()}">${escapeHtml(b.type)}</span><span>${escapeHtml(b.sport)}</span><span>${escapeHtml(b.date)}</span></div><strong class="bet-wager">${escapeHtml(b.wager)}</strong>${legs}</div><div class="bet-figure"><small>Stake</small><strong>${currency(b.stake)}</strong></div><div class="bet-figure"><small>Odds</small><strong>${b.odds>0?"+":""}${b.odds}</strong></div><div class="bet-figure potential"><small>To win</small><strong>${currency(potentialProfit)}</strong></div><div class="bet-result"><select class="result-select" data-id="${b.id}" aria-label="Result for ${escapeHtml(b.wager)}"><option ${b.result==="Pending"?"selected":""}>Pending</option><option ${b.result==="Win"?"selected":""}>Win</option><option ${b.result==="Loss"?"selected":""}>Loss</option><option ${b.result==="Push"?"selected":""}>Push</option></select><strong class="net-result ${b.result.toLowerCase()}">${currency(getProfit(b))}</strong></div><button class="delete-button" data-type="bet" data-id="${b.id}">Delete</button></article>`;
  }).join(""):"<div class=\"empty-row\">No bets recorded yet.</div>";
  renderPlayerExposure();
}

function renderPlayerExposure(){
  const exposure = new Map(), totalBuyIn = leagues.reduce((sum, league) => sum + Number(league.buyIn || 0), 0);
  leagues.forEach(league => { const seenInLeague = new Set(); (league.roster || []).forEach(player => {
    const key = player.name.trim().toLowerCase(); if (!key) return;
    if (seenInLeague.has(key)) return; seenInLeague.add(key);
    const item = exposure.get(key) || { name: player.name.trim(), position: player.position, leagues: 0, buyIn: 0 };
    item.leagues += 1; item.buyIn += Number(league.buyIn || 0); exposure.set(key, item);
  }); });
  const players = [...exposure.values()].sort((a,b) => b.leagues - a.leagues || b.buyIn - a.buyIn || a.name.localeCompare(b.name));
  document.getElementById("playerExposureList").innerHTML = players.length ? players.map(player => {
    const leaguePercent = leagues.length ? Math.round(player.leagues / leagues.length * 100) : 0;
    const buyInPercent = totalBuyIn ? Math.round(player.buyIn / totalBuyIn * 100) : null;
    return `<div class="exposure-row"><div class="exposure-player"><span class="position-badge ${positionClass(player.position)}">${escapeHtml(player.position || "Player")}</span><div><strong>${escapeHtml(player.name)}</strong><small>${player.leagues} of ${leagues.length} league${leagues.length === 1 ? "" : "s"}</small></div></div><div class="exposure-meter" aria-label="${leaguePercent}% league exposure"><div class="exposure-meter-label"><span>League exposure</span><strong>${leaguePercent}%</strong></div><span><i style="width:${leaguePercent}%"></i></span></div><div class="exposure-stat"><strong>${buyInPercent === null ? "—" : `${buyInPercent}%`}</strong><small>buy-in exposure</small></div></div>`;
  }).join("") : "<div class=\"empty-row\">Add players to a league roster to see your exposure.</div>";
}
async function loadCloudData(){ if(!currentUser)return; const [lr,br,dr]=await Promise.all([supabaseClient.from("leagues").select("*").order("created_at",{ascending:false}),supabaseClient.from("bets").select("*").order("created_at",{ascending:false}),supabaseClient.from("daily_fantasy_entries").select("*").order("created_at",{ascending:false})]); const error=lr.error||br.error; if(error)throw error; leagues=lr.data.map(rowToLeague);bets=br.data.map(rowToBet);if(!dr.error)dailyFantasy=dr.data.map(rowToDailyFantasy); saveLocalData();render(); }
async function migrateLocalData(){if(!currentUser||localStorage.getItem(MIGRATION_KEY)===currentUser.id)return;const localL=JSON.parse(localStorage.getItem(LEAGUES_KEY)||"[]"),localB=JSON.parse(localStorage.getItem(BETS_KEY)||"[]"),localD=JSON.parse(localStorage.getItem(DAILY_FANTASY_KEY)||"[]");if(localL.length){const {error}=await supabaseClient.from("leagues").upsert(localL.map(leagueToRow));if(error)throw error;}if(localB.length){const {error}=await supabaseClient.from("bets").upsert(localB.map(betToRow));if(error)throw error;}if(localD.length){const {error}=await supabaseClient.from("daily_fantasy_entries").upsert(localD.map(dailyFantasyToRow));if(error)throw error;}localStorage.setItem(MIGRATION_KEY,currentUser.id);}
async function saveLeague(l){if(!currentUser){leagues.unshift(l);saveLocalData();render();return;}const {error}=await supabaseClient.from("leagues").insert(leagueToRow(l));if(error)throw error;await loadCloudData();}
async function saveBet(b){if(!currentUser){bets.unshift(b);saveLocalData();render();return;}const {error}=await supabaseClient.from("bets").insert(betToRow(b));if(error)throw error;await loadCloudData();}
async function saveDailyFantasy(entry){if(!currentUser){dailyFantasy.unshift(entry);saveLocalData();render();return;}const {error}=await supabaseClient.from("daily_fantasy_entries").insert(dailyFantasyToRow(entry));if(error)throw error;await loadCloudData();}
async function updateLeagueRoster(){if(!editingLeague)return; const roster=[...document.querySelectorAll(".roster-row")].map(row=>({name:row.querySelector("input").value.trim(),position:row.querySelector("select").value})).filter(p=>p.name);editingLeague.roster=roster;if(!currentUser){saveLocalData();render();return;}const {error}=await supabaseClient.from("leagues").update({roster}).eq("id",editingLeague.id);if(error)throw error;await loadCloudData();}
async function updateBetResult(id,result){if(!currentUser){const b=bets.find(x=>x.id===id);if(b)b.result=result;saveLocalData();render();return;}const {error}=await supabaseClient.from("bets").update({result}).eq("id",id);if(error)throw error;await loadCloudData();}
async function updateLeagueResult(id, changes){if(!currentUser){const league=leagues.find(x=>x.id===id);if(league)Object.assign(league,changes);saveLocalData();render();return;}const payload={};if("result" in changes)payload.result=changes.result;if("amount" in changes)payload.payout=changes.amount;const {error}=await supabaseClient.from("leagues").update(payload).eq("id",id);if(error)throw error;await loadCloudData();}
async function updateDailyFantasy(id, changes){if(!currentUser){const entry=dailyFantasy.find(x=>x.id===id);if(entry)Object.assign(entry,changes);saveLocalData();render();return;}const {error}=await supabaseClient.from("daily_fantasy_entries").update(changes).eq("id",id);if(error)throw error;await loadCloudData();}
async function deleteEntry(type,id){if(!currentUser){if(type==="league")leagues=leagues.filter(x=>x.id!==id);else if(type==="daily")dailyFantasy=dailyFantasy.filter(x=>x.id!==id);else bets=bets.filter(x=>x.id!==id);saveLocalData();render();return;}const table=type==="league"?"leagues":type==="daily"?"daily_fantasy_entries":"bets";const {error}=await supabaseClient.from(table).delete().eq("id",id);if(error)throw error;await loadCloudData();}
function rosterRow(p={name:"",position:"WR"}){return `<div class="roster-row"><input value="${escapeHtml(p.name)}" placeholder="Player name"><select><option ${p.position==="QB"?"selected":""}>QB</option><option ${p.position==="RB"?"selected":""}>RB</option><option ${p.position==="WR"?"selected":""}>WR</option><option ${p.position==="TE"?"selected":""}>TE</option><option ${p.position==="K"?"selected":""}>K</option><option ${p.position==="DEF"?"selected":""}>DEF</option></select><button type="button" class="delete-button remove-roster-player">Remove</button></div>`;}
function openRoster(id){editingLeague=leagues.find(l=>l.id===id);if(!editingLeague)return;document.getElementById("rosterTitle").textContent=`${editingLeague.team||editingLeague.name} roster`;document.getElementById("rosterPlayers").innerHTML=editingLeague.roster.map(rosterRow).join("")||"<p class=\"empty-row\">No players yet — add your first player below.</p>";document.getElementById("rosterDialog").showModal();}

document.getElementById("profileButton").addEventListener("click",()=>{const m=document.getElementById("profileMenu"),open=m.hidden;m.hidden=!open;document.getElementById("profileButton").setAttribute("aria-expanded",open);});
document.addEventListener("click",e=>{const wrap=e.target.closest(".profile-wrap");if(!wrap)document.getElementById("profileMenu").hidden=true;});
document.getElementById("authForm").addEventListener("submit",async e=>{e.preventDefault();const {error}=await supabaseClient.auth.signInWithPassword({email:authEmail.value.trim(),password:authPassword.value});if(error)showMessage(error.message,true);});
document.getElementById("signUpButton").addEventListener("click",async()=>{const {data,error}=await supabaseClient.auth.signUp({email:authEmail.value.trim(),password:authPassword.value,options:{emailRedirectTo:location.href}});if(error)showMessage(error.message,true);else if(!data.session)showMessage("Check your email to confirm your account, then sign in.");});document.getElementById("signOutButton").addEventListener("click",()=>supabaseClient.auth.signOut());
document.getElementById("fantasyForm").addEventListener("submit",async e=>{e.preventDefault();try{await saveLeague({id:crypto.randomUUID(),name:leagueName.value.trim(),platform:leaguePlatform.value.trim(),team:teamName.value.trim(),buyIn:Number(leagueBuyIn.value),status:leagueStatus.value,result:leagueResult.value,amount:Number(leaguePayout.value),roster:[]});e.target.reset();leagueBuyIn.value=0;leaguePayout.value=0;}catch(error){showMessage(`Could not save league: ${error.message}`,true);}});
function parlayLegField(index){return `<label class="bet-leg"><span>${index === 0 ? "Wager" : `Parlay leg ${index + 1}`}</span><input class="bet-leg-input" required placeholder="${index === 0 ? "Chiefs -3.5" : "Add another selection"}">${index ? '<button type="button" class="delete-button remove-leg-button" aria-label="Remove parlay leg">Remove</button>' : ""}</label>`;}
function resetBetLegs(){document.getElementById("betLegs").innerHTML=parlayLegField(0);}
document.getElementById("addParlayLeg").addEventListener("click",()=>{const container=document.getElementById("betLegs");container.insertAdjacentHTML("beforeend",parlayLegField(container.querySelectorAll(".bet-leg").length));container.querySelector(".bet-leg:last-child input").focus();});
document.getElementById("betForm").addEventListener("submit",async e=>{e.preventDefault();const legs=[...document.querySelectorAll(".bet-leg-input")].map(input=>input.value.trim()).filter(Boolean);const isParlay=legs.length>1;if(!legs.length){showMessage("Add a wager before saving the bet.",true);return;}try{await saveBet({id:crypto.randomUUID(),date:betDate.value,type:isParlay?"Parlay":"Single",sport:betSport.value.trim(),wager:isParlay?`${legs.length}-Leg Parlay`:legs[0],legs:isParlay?legs:[],stake:Number(betStake.value),odds:Number(betOdds.value),result:betResult.value});e.target.reset();betDate.valueAsDate=new Date();resetBetLegs();}catch(error){showMessage(`Could not save bet: ${error.message}`,true);}});
document.getElementById("dailyFantasyForm").addEventListener("submit",async e=>{e.preventDefault();try{await saveDailyFantasy({id:crypto.randomUUID(),date:dailyFantasyDate.value,type:dailyFantasyType.value.trim(),slate:dailyFantasySlate.value.trim(),site:dailyFantasySite.value.trim(),result:dailyFantasyResult.value,amount:Number(dailyFantasyAmount.value)});e.target.reset();dailyFantasyDate.valueAsDate=new Date();dailyFantasyAmount.value="";}catch(error){showMessage(`Could not save daily fantasy entry: ${error.message}`,true);}});
document.addEventListener("change",async e=>{try{if(e.target.matches(".fantasy-result-select"))await updateLeagueResult(e.target.dataset.id,{result:e.target.value});else if(e.target.matches(".fantasy-amount-input"))await updateLeagueResult(e.target.dataset.id,{amount:Number(e.target.value)||0});else if(e.target.matches(".daily-result-select"))await updateDailyFantasy(e.target.dataset.id,{result:e.target.value});else if(e.target.matches(".daily-amount-input"))await updateDailyFantasy(e.target.dataset.id,{amount:Number(e.target.value)||0});else if(e.target.matches(".result-select"))await updateBetResult(e.target.dataset.id,e.target.value);}catch(error){showMessage(error.message,true);}});
document.addEventListener("click",async e=>{const roster=e.target.closest(".roster-button"),edit=e.target.closest(".edit-roster"),del=e.target.closest(".delete-button");if(roster){expandedLeagueId=expandedLeagueId===roster.dataset.id?null:roster.dataset.id;render();return;}if(edit)return openRoster(edit.dataset.id);if(e.target.matches(".remove-roster-player")){e.target.closest(".roster-row").remove();return;}if(e.target.matches(".remove-leg-button")){e.target.closest(".bet-leg").remove();return;}if(!del)return;try{await deleteEntry(del.dataset.type,del.dataset.id);}catch(error){showMessage(error.message,true);}});
document.getElementById("addRosterPlayer").addEventListener("click",()=>{const name=rosterPlayerName.value.trim();if(!name)return;const empty=document.querySelector("#rosterPlayers .empty-row");if(empty)empty.remove();document.getElementById("rosterPlayers").insertAdjacentHTML("beforeend",rosterRow({name,position:rosterPlayerPosition.value}));rosterPlayerName.value="";});document.getElementById("closeRoster").addEventListener("click",()=>rosterDialog.close());document.getElementById("rosterForm").addEventListener("submit",async e=>{e.preventDefault();try{await updateLeagueRoster();rosterDialog.close();}catch(error){rosterError.textContent=`Could not save roster: ${error.message}`;}});
supabaseClient.auth.onAuthStateChange(async(_event,session)=>{currentUser=session?.user||null;setAuthUI();if(!currentUser){render();return;}try{await migrateLocalData();await loadCloudData();}catch(error){showMessage(`Cloud sync needs setup: ${error.message}`,true);}});
window.addEventListener("focus",()=>{if(currentUser)loadCloudData().catch(e=>showMessage(e.message,true));});setInterval(()=>{if(currentUser)loadCloudData().catch(()=>{});},15000);betDate.valueAsDate=new Date();dailyFantasyDate.valueAsDate=new Date();render();
